input {
  beats {
    port => 5044
  }
}

filter {
  if [log_type] == "snort" {
    grok {
      match => {
        "message" => "%{MONTHNUM:month}/%{MONTHDAY:day}-%{TIME:time}\s+\[\*\*\]\s+\[%{INT:gid}:%{INT:sid}:%{INT:rev}\]\s+%{DATA:alert_message}\s+\[\*\*\]\s+\[Classification:\s+%{DATA:classification}\]\s+\[Priority:\s+%{INT:priority}\]\s+\{%{WORD:protocol}\}\s+%{IP:src_ip}:%{INT:src_port}\s+->\s+%{IP:dst_ip}:%{INT:dst_port}"
      }
    }

    mutate {
      add_field => { "event_type" => "snort_alert" }
    }
  }
}

output {
  if [log_type] == "snort" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "snort-alerts-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
