FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    nginx \
    vsftpd \
    curl \
    iproute2 \
    net-tools \
    procps \
    snort \
    net-tools \
    iproute2 \
    vim \
    snort oinkmaster && \
    mkdir -p /usr/local/lib/snort_dynamicpreprocessor/ \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/html \
    /srv/ftp \
    /var/log/nginx \
    /var/log/vsftpd \
    /run/vsftpd/empty

# Crear directorio de logs
RUN mkdir -p /var/log/snort

# Copiar un archivo de configuración base (puedes personalizar después)
RUN cp /etc/snort/snort.conf.example /etc/snort/snort.conf || true

COPY nginx.conf /etc/nginx/nginx.conf
COPY vsftpd.conf /etc/vsftpd.conf
COPY start.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 80 21 40000-40010

CMD ["/start.sh"]








